### ISSUE TITLE
Publish on NuGet.

### ISSUE THREAD

**Issue by amatkivskiy** [jacksierkstra/Picasso#6]
Hi, thanks for  Picasso binding but can't we publish this on NuGet to use it as package?

**Comment by kenkyee** [comment]
Ditto..please publish on NuGet :-)

**Comment by amatkivskiy** [comment]
@kenkyee It doesn't matter anymore. **mattleibow** already published it [here](https://www.nuget.org/packages/Square.Picasso/).

**Comment by kenkyee** [comment]
Thanks...I found the mattleibow one already last week :-)
Conflicts w/ modernhttpclient though :-P

**Comment by amatkivskiy** [comment]
@kenkyee what about okhhtp bindings for that case.

**Comment by kenkyee** [comment]
problem in Xamarin is you can't exclude packages.
Both Square.Picasso and modernhttpclient include a dependency on okhttp and Square.okhttp.  Two separate packages w/ the same class names :-(
